---
- hosts: localhost
  vars_files:
    - vars/main.yml
  roles:
    - role: software-common-non-gui
      tags: non-gui
    - role: gantsign.antigen
      tags: zsh
    - role: software-common-gui
      tags: gui
    - role: languages
      tags: langs
