---
# tasks file for software-common-non-gui
- name: install common packages
  apt:
    pkg:
      - vim
      - tmux
      - python3-venv
      - curl
      - gcc
      - build-essential
      - aspell

- name: clone Tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: create Tmux conf file with plugins
  copy:
    dest: ~/.tmux.conf
    content: |
      set-option -g status-position top
      set-option -g repeat-time 0
      # List of plugins
      set -g @plugin 'tmux-plugins/tpm'
      set -g @plugin 'tmux-plugins/tmux-sensible'
      set -g @plugin 'tmux-plugins/tmux-resurrect'
      # Initialize TMUX plugin manager (TPM) - (keep this line at the very bottom of tmux.conf)
      run '~/.tmux/plugins/tpm/tpm'
