---
# tasks file for zsh-theme-p10k
- name: 🐑 clone p10k theme
  become: true
  become_user: '{{ default_user }}'
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: 1
    dest: /home/{{ default_user }}/.powerlevel10k

- name: 🖊 set zsh theme to pk10
  become: true
  become_user: '{{ default_user }}'
  lineinfile:
    path: /home/{{ default_user }}/.zshrc
    line: source ~/.powerlevel10k/powerlevel10k.zsh-theme

- name: 📁 create fonts directory
  become: true
  file:
    path: /usr/share/fonts/truetype/meslo-lgs
    mode: '0755'
    state: directory

- name: 📥 install p10k recommended fonts
  become: true
  copy:
    src: "fonts/{{ item }}"
    dest: "/usr/share/fonts/truetype/meslo-lgs/{{ item }}"
    mode: '0644'
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf
